name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  KERNEL_CL: kernels/kernel.cl
  TEST_CONFIG: configs/test.json

jobs:
  build-and-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt install -y gcc g++ clang
          sudo apt install -y opencl-c-headers opencl-clhpp-headers ocl-icd-opencl-dev
          sudo apt install -y pocl-opencl-icd
          sudo apt install -y oclgrind

      - name: build
        run: make

      - name: run
        run: |
          mkdir data
          echo "Starting simulations..."
          POCL_DEVICES=basic ./build/bubbleSim.exe $TEST_CONFIG $KERNEL_CL &> log_basic.txt
          echo "Finished basic..."
          cat log_basic.txt
          POCL_DEVICES=pthread ./build/bubbleSim.exe $TEST_CONFIG $KERNEL_CL &> log_pthread.txt
          cat log_pthread.txt
          echo "Finished pthread..."

          diff log_basic.txt log_pthread.txt > diff1.txt || true
          export NUMDIFF=$(wc -l < diff1.txt)
          echo "diff lines "$NUMDIFF

          #fail if there are more than 10 lines of difference between the two logs
          if [[ $NUMDIFF -ge 10 ]] ; then
            echo "too many differences, failing"
            exit 1
          fi
      
      - name: build with O3
        run: |
          make clean
          OPTFLAGS=-O3 make -j4
          POCL_DEVICES=pthread ./build/bubbleSim.exe $TEST_CONFIG $KERNEL_CL &> log_pthread_O3.txt

          diff log_pthread.txt log_pthread_O3.txt > diff2.txt || true
          export NUMDIFF=$(wc -l < diff2.txt)
          echo "diff lines "$NUMDIFF

          #fail if there are more than 10 lines of difference between the two logs
          if [[ $NUMDIFF -ge 10 ]] ; then
            echo "too many differences, failing"
            exit 1
          fi

      - name: build with clang
        run: |
          make clean
          CXX=clang make -j4
          POCL_DEVICES=pthread ./build/bubbleSim.exe $TEST_CONFIG $KERNEL_CL &> log_pthread_clang.txt

          diff log_pthread.txt log_pthread_clang.txt > diff3.txt || true
          export NUMDIFF=$(wc -l < diff3.txt)
          echo "diff lines "$NUMDIFF

          #fail if there are more than 10 lines of difference between the two logs
          if [[ $NUMDIFF -ge 10 ]] ; then
            echo "too many differences, failing"
            exit 1
          fi

      - name: oclgrind
        run: |
          make clean
          make -j4
          oclgrind --data-races --uninitialized --log oclgrind.log ./build/bubbleSim.exe configs/test_oclgrind.json $KERNEL_CL &> log_oclgrind.txt
          tail -n10 oclgrind.log
          
          #fail if oclgrind.log is not empty
          if [[ -s oclgrind.log ]] ; then
            echo "oclgrind log is not empty"
            exit 1
          fi

      - name: asan
        run: |
          make clean
          OPTFLAGS="-O0 -fsanitize=address -g" make
          ASAN_OPTIONS="verbose=1,abort_on_error=1" ./build/bubbleSim.exe $TEST_CONFIG $KERNEL_CL &> log_asan.txt

