name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt install -y gcc g++
          sudo apt install -y opencl-c-headers opencl-clhpp-headers ocl-icd-opencl-dev
          sudo apt install -y pocl-opencl-icd
          sudo apt install -y oclgrind
      - name: build
        run: make
      - name: run
        run: |
          mkdir data
          POCL_DEVICES=basic ./build/bubbleSim.exe bubbleSim/config.json
          oclgrind ./build/bubbleSim.exe bubbleSim/config.json
