name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt install -y gcc g++
          sudo apt install -y opencl-c-headers opencl-clhpp-headers ocl-icd-opencl-dev
          sudo apt install -y pocl-opencl-icd
          ls -lrt /usr/lib/x86_64-linux-gnu/libOpenCL*
          ls -lrt /usr/lib/x86_64-linux-gnu/libpocl*
          gcc --version
      - name: build
        run: make
      - name: run
        run: |
          mkdir data
          ./build/bubbleSim.exe
