name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt install -y opencl-c-headers opencl-clhpp-headers
          sudo apt install -y pocl-opencl-icd
      - name: build
        run: make
