name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt install -y gcc g++
          sudo apt install -y opencl-c-headers opencl-clhpp-headers ocl-icd-opencl-dev
          sudo apt install -y pocl-opencl-icd
          sudo apt install -y oclgrind
      - name: build
        run: make
      - name: run
        run: |
          mkdir data
          POCL_DEVICES=pthread ./build/bubbleSim.exe bubbleSim/config.json &> log_pthread.txt
          head -n10 log_pthread.txt
          tail -n10 log_pthread.txt

          POCL_DEVICES=basic ./build/bubbleSim.exe bubbleSim/config.json &> log_basic.txt
          head -n10 log_basic.txt
          tail -n10 log_basic.txt
      - name: oclgrind
          oclgrind ./build/bubbleSim.exe bubbleSim/config.json &> log_oclgrind.txt
          head -n10 log_basic.txt
          tail -n10 log_basic.txt
      - name: asan
        run: |
          OPTFLAGS="-O0 -fsanitize=address -g" make
          ./build/bubbleSim.exe bubbleSim/config.json &> log_asan.txt
          head -n10 log_asan.txt
          tail -n10 log_asan.txt
           
